services:
  gotify-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gotify-mcp
    labels:
      - com.centurylinklabs.watchtower.enable=false
    ports:
      - ${GOTIFY_MCP_PORT:-9158}:${GOTIFY_MCP_PORT:-9158}
    env_file:
      - .env
    volumes:
      - ${APPDATA_PATH}/gotify-mcp/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:${GOTIFY_MCP_PORT:-9158}/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - jakenet
networks:
  jakenet:
    external: true
